### ISSUE TITLE
4.1 TAR file unreachable

### ISSUE THREAD

**Issue by fherbet** [dleidert/openmediavault-upgrade#2]
Hey !

1st of all thanks for this repo, it's huge!
i'm quite interested by your update script as my MicroGen8 / OMV4.1 / Docker doesn't have required PHP7.2 to run Nextcloud Cronjob... i'd like to update to OMV5

so i deactivated all services including docker (only SSH left / screen session on) but here's what i get ... tar file looks unreachable!

```
 wget  https://github.com/dleidert/openmediavault-upgrade/archive/4.1.tar.gz
--2020-12-30 12:19:40--  https://github.com/dleidert/openmediavault-upgrade/archive/4.1.tar.gz
Résolution de github.com (github.com)… 140.82.121.4
Connexion à github.com (github.com)|140.82.121.4|:443… connecté.
requête HTTP transmise, en attente de la réponse… 302 Found
Emplacement : https://codeload.github.com/dleidert/openmediavault-upgrade/tar.gz/4.1 [suivant]
--2020-12-30 12:19:40--  https://codeload.github.com/dleidert/openmediavault-upgrade/tar.gz/4.1
Résolution de codeload.github.com (codeload.github.com)… 140.82.121.10
Connexion à codeload.github.com (codeload.github.com)|140.82.121.10|:443… connecté.
requête HTTP transmise, en attente de la réponse… 404 Not Found
2020-12-30 12:19:41 erreur 404 : Not Found.
```

can you please check ? think it's not hard to fix ;-)

thanks again!
\\ fherbet

**Comment by fherbet** [comment]
ok found the typo

in README.md

v is missing before 4.1.tar.gz
`wget  https://github.com/dleidert/openmediavault-upgrade/archive/4.1.tar.gz`

should be 
`wget https://github.com/dleidert/openmediavault-upgrade/archive/v4.1.tar.gz `

**Comment by dleidert** [comment]
Yes. I change the tags from `X.Y` to `vX.Y` but missed to fix the READMEs.

**Comment by dleidert** [comment]
Fixed in all the READMEs

**Comment by dleidert** [comment]
Let me know how it went :)

**Comment by fherbet** [comment]
thanks i'll do that tonight after business hours ;-) and i'll let you know

there's another typo related to "screen" procedure :
`sudo pt-get install -y screen`

**Comment by dleidert** [comment]
Thanks. Fixed that too.

**Comment by fherbet** [comment]
it went absolutely fine ! just used 4.4 and i just had to stop my docker containers and `apt install docker-ce` post install...

awesome piece of work mate... thanks a million!

**Comment by dleidert** [comment]
> i just had to stop my docker containers and `apt install docker-ce` post install...

The upcoming 4.5 release will remove the plugin but keep docker-ce. So this should be fixed then too.
