### ISSUE TITLE
Upgrade and "not Debian 'stretch'"

### ISSUE THREAD

**Issue by binerf** [dleidert/openmediavault-upgrade#38]
Hi All,

I'm trying to upgrde my OMV from 4 to 5 thanks to the script omv-release-upgrade-5 just download from github.
When I execute the script, I get this error:
```
 ./omv-release-upgrade-5 
2021-05-03T16:44:21,946445132+02:00
run-parts: executing /root/openmediavault-upgrade-4.7/check.d/01-debian-version
You are trying to run this script from Debian '10.9', not Debian 'stretch'.
run-parts: /root/openmediavault-upgrade-4.7/check.d/01-debian-version exited with return code 1
```
In the past, I get used to update via `omv-update` command.

What can I do please ?

**Comment by godfuture** [comment]
I looks like you are already on omv 5 or something in between. Have you executed `omv-update` before executing these scripts here? If yes, you should try to find out what is supposed to happen on `omv-update`. I was testing these scripts without `omv-update` and they worked like a charm.

**Comment by binerf** [comment]
Yep, I guess you're right, I'm in something between.
I guess I performed someday an `aptitude dist-upgrade` which upgraded Debian but not OMV.

How is it possible to fix and keep using the `omv-release-upgrade-5` script ?

**Comment by godfuture** [comment]
> Yep, I guess you're right, I'm in something between.
> I guess I performed someday an `aptitude dist-upgrade` which upgraded Debian but not OMV.
> 
> How is it possible to fix and keep using the `omv-release-upgrade-5` script ?

These scripts here are not helping, because they require to prepare the system before upgrade. I guess it is also too complex for the author to decide whether a part of it is enough to make it work in the end.

It sounds ridiculous, but I guess going back to old state is the easiest. If you do not have a backup, than there is a guide in omv forum that explains manual changes after dist upgrade.

**Comment by binerf** [comment]
> These scripts here are not helping, because they require to prepare the system before upgrade. I guess it is also too complex for the author to decide whether a part of it is enough to make it work in the end.
> 
> It sounds ridiculous, but I guess going back to old state is the easiest. If you do not have a backup, than there is a guide in omv forum that explains manual changes after dist upgrade.
Thanks for your feedback.
Not ridiculous, just hard to do.

I'll check in the forum for this documentation but, if you already have it somewhere (direct link), I'll appreciate.

Thanks !

**Comment by godfuture** [comment]
> I'll check in the forum for this documentation but, if you already have it somewhere (direct link), I'll appreciate.

https://forum.openmediavault.org/index.php?thread/29547-solved-upgrade-from-omv-4-to-omv5
https://blog.sakuragawa.moe/upgrade-omv-4-to-5-a-painful-path

Well, I know these threads are endless. But I think you might tackle issue by issue. Not nice at all. But what can you do without backup?

**Comment by mi-hol** [comment]
Please close this issue

**Comment by binerf** [comment]
Thanks for your recommandation and sorry for the late feedback.
