### ISSUE TITLE
Failed upgrade due to Debian 9/stretch move to archive.debian.org

### ISSUE THREAD

**Issue by DarS007** [dleidert/openmediavault-upgrade#48]
I just attempted to upgrade my 4.1.36 Arrakis to OMV 5 (Usul), but the script failed with the following output:
`Reading package lists...`
`E: The repository 'http://ftp.icm.edu.pl/pub/Linux/debian stretch Release' does no longer have a Release file.`
`E: The repository 'http://ftp.icm.edu.pl/pub/Linux/debian stretch-updates Release' does no longer have a Release file.`
`E: The repository 'http://security.debian.org/debian-security stretch/updates Release' does no longer have a Release file.`
`run-parts: /home/USER/openmediavault-upgrade-4.7/run.d/10-apt-update exited with return code 100
`

Further search revealed _Debian 9/stretch moved to archive.debian.org_ message (https://lists.debian.org/debian-devel-announce/2023/03/msg00006.html) from Mon, 27 Mar 2023 with significant changes in _stretch_ repositories:

_Hi, 
the stretch, stretch-debug and stretch-proposed-updates suites have now also been imported on ''archive.debian.org''. People still interested in these should update their sources.list. 
I plan to remove the suites from the main archive in about a month (2023-04-23 or later)._

So perhaps the stretch move to ''archive.debian.org'' already happened, causing the errors I encountered. Can you please adjust your OMV upgrade script to properly handle these stretch repo changes?

Thanks in advance!
-DarS007

**Comment by mi-hol** [comment]
FYI, it seems dleidert has abandoned this repo, so you are on your own to fix this issue

**Comment by DarS007** [comment]
@mi-hol  - OK, thanks for the info!

**Comment by DarS007** [comment]
closing then due to lack of the repo owner
